### ISSUE TITLE
1.2.1-1.7.10 dependency not compiling

### ISSUE THREAD

**Issue by Lyl4c** [iLexiconn/LLibrary#1]
repositories {
    maven {
        name = "ilexiconn"
        url = "http://maven.ilexiconn.net"
    }
}

dependencies {
    compile "net.ilexiconn:llibrary:1.2.1-1.7.10:dev"
}

forge 10.13.4.1614

1.0.0-1.7.10 works fine, but I can't get this latest version to work using this method

**Comment by iLexiconn** [comment]
Whoops, fixed! =)
