### ISSUE TITLE
llibrary 1.5.0 problem crash when die

### ISSUE THREAD

**Issue by ryanhensman** [iLexiconn/LLibrary#10]
Hello im using llibrary 1.5.0 for 1.9.4 minecraft and a mod called JurassiCraft 2.0.0, we having been having issues where everytime we die the game crashes out and comes up with a error message ile drop in the error code as we cant figure out a way to fix this issue. Hope you can help. this is on solo and when we try playing lan.

Minecraft Crash Report ----
WARNING: coremods are present:
llibrary (llibrary-1.5.0-1.9.4.jar)
Contact their authors BEFORE contacting forge
// Daisy, daisy...
Time: 29/07/16 22:44
Description: Exception in server tick loop
java.lang.UnsupportedOperationException
at java.util.Collections$UnmodifiableCollection$1.remove(Collections.java:1044)
at net.ilexiconn.llibrary.server.ServerEventHandler.onServerTickEvent(ServerEventHandler.java:173)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_9_ServerEventHandler_onServerTickEvent_ServerTickEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:254)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
Minecraft Version: 1.9.4
Operating System: Windows 8 (amd64) version 6.2
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 246492384 bytes (235 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
FML: MCP 9.28 Powered by Forge 12.17.0.1990 5 mods loaded, 5 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAAAA mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
UCHIJAAAA FML{8.0.99.99} [Forge Mod Loader](forge-1.9.4-12.17.0.1990.jar) 
UCHIJAAAA Forge{12.17.0.1990} [Minecraft Forge](forge-1.9.4-12.17.0.1990.jar)
UCHIJAAAA llibrary{1.5.0} [LLibrary](llibrary-1.5.0-1.9.4.jar) 
UCHIJAAAA jurassicraft{2.0.0} [JurassiCraft](JurassiCraft-2.0.0.jar) 
Loaded coremods (and transformers): 
llibrary (llibrary-1.5.0-1.9.4.jar)
net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
Profiler Position: N/A (disabled)
Player Count: 1 / 8; [EntityPlayerMP['Smileyboi93'/746, l='New World', x=-109.50, y=69.00, z=238.50]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by iLexiconn** [comment]
Fixed in next version

**Comment by ryanhensman** [comment]
when is next version out

**Comment by iLexiconn** [comment]
This week
