### ISSUE TITLE
Crash on game launch

### ISSUE THREAD

**Issue by CTLDragon19** [iLexiconn/LLibrary#100]
I have the latest update and i tried with all the mods out and just launched it normally and still crashed
[latest.log](https://github.com/iLexiconn/LLibrary/files/2612349/latest.log)

**Comment by iPlays04** [comment]
i have the same problem, please fix it!

**Comment by SonicX8000** [comment]
To add onto this...

Forge Versions 14.23.5.2779 and up is what causes the crash upon startup with 'llibrary-1.7.15-1.12.2', older Forge Versions below that do not seem to cause this issue to happen.

**Comment by AfterRebelion** [comment]
To specify, it is most probably done by [a change in this PR](https://github.com/MinecraftForge/MinecraftForge/pull/4853)

**Comment by jredfox** [comment]
hey it appears that it crashes without my library. Basically the method of net/minecraftforge/client/ForgeHooksClient.invalidateLog4jThreadCache()V  was either removed changed or modified and your asm isn't compatible. if you are replacing a class do not use method replacements.

To fix this don't remove or replace method throwables or returns. If the method doesn't exist add it or have some sort of version check

**Comment by AfterRebelion** [comment]
Ohh... if it is related to invalidateLog4jThreadCache, that was added on [this PR](https://github.com/MinecraftForge/MinecraftForge/pull/5078), that shipped on 14.23.5.2779 too... so that makes sense.

**Comment by Drezkil** [comment]
Download this version it will fix everithing 
llibrary-1.7.9-1.12.2

**Comment by jredfox** [comment]
the goal here is to fix it for the latest version. I have pointed out exactly what method and class of asm is the issue here so they should be able to fix it pretty easily

**Comment by Gegy** [comment]
Resolved in 1.7.16. :)
