### ISSUE TITLE
[1.17.6] crash upon loading world

### ISSUE THREAD

**Issue by lag42** [iLexiconn/LLibrary#105]
https://hastebin.com/voqebefije.cs
i'm using forge 2795
and only llibrary is installed in this instance

**Comment by Drake808** [comment]
[crash-2018-12-05_15.09.44-client.txt](https://github.com/iLexiconn/LLibrary/files/2651019/crash-2018-12-05_15.09.44-client.txt)

**Comment by Drake808** [comment]
same man

**Comment by Gegy** [comment]
1.7.17 has been released to fix this. Looks like my buildscript messed up and didn't obfuscate anything! Odd.
