### ISSUE TITLE
[1.12.2] Crash upon loading a World.

### ISSUE THREAD

**Issue by SonicX8000** [iLexiconn/LLibrary#107]
Minecraft: 1.12.2
Forge: 14.23.5.2795

Mods: 1
llibrary-1.7.16-1.12.2

Crash Report:
https://pastebin.com/XDEjcT3s

-----
Upon loading a world... I get a frozen blank screen, followed by a crash a few seconds later.

**Comment by Gegy** [comment]
1.7.17 has been released to fix this. Looks like my buildscript messed up and didn't obfuscate anything! Odd.
