### ISSUE TITLE
PropertiesTracker#updateTracker performance

### ISSUE THREAD

**Issue by Sir-Will** [iLexiconn/LLibrary#111]
hey,

not sure for what this is used for but time seems to be a lot for this.
![](https://i.imgur.com/WjjaMfh.jpg)

llibrary-1.7.15-1.12.2
iceandfire-1.5.2

**Comment by Gegy** [comment]
Yeah, unfortunately the code was not designed too well. Changing it would be a breaking change, though. Will have to wait until a breaking update. Also, closing in favour of #91.
