### ISSUE TITLE
wat.error

### ISSUE THREAD

**Issue by Sunconure11** [iLexiconn/LLibrary#112]
https://paste.dimdev.org/ofuvedubuv.mccrash

**Comment by Gegy** [comment]
Can you send a full log? This can only happen if Forge fails to extract the contained LLibraryCore dependency.

**Comment by Sunconure11** [comment]
Lost the log when another error struck, relating to contenttweaker

**Comment by Sunconure11** [comment]
Okay, it's possible there may be a reference to this crash in my log, you can sift if you desire.

https://gist.github.com/Sunconure11/a40c861a3a813cb59b140035d29247b5

**Comment by Gegy** [comment]
In that log it seems to have extracted successfully.
