### ISSUE TITLE
[1.12.2] LLibrary mixin re-entrance?

### ISSUE THREAD

**Issue by Luke616** [iLexiconn/LLibrary#117]
Honestly not really sure what the cause of this issue is, but it seems to be related to LLibrary so I thought I would try to post here. I've added LLibrary and Wings to a modpack I'm working on, but minecraft began throwing this error on load:

https://pastebin.com/j7a4TmZE

However, when I hit "play" a second time after this error is thrown, the game loads up just fine. Any idea what would be the cause of it? If this is not the right place to post or if you need more information please let me know.

Versions:
Minecraft 1.12.2
Forge 14.23.5.2796 
LLibrary 1.7.17
Wings 1.1.2

**Comment by comp500** [comment]
I have managed to reliably reproduce this crash by deleting `config/vanillafix/methods-stable_39.csv` every time before starting the game.

Log: https://paste.ee/p/9yykf
Versions: (full mod list, no other mods installed)
- Minecraft 1.12.2
- Forge 14.23.5.2807
- LLibrary 1.7.17
- Wings 1.1.2
- VanillaFix 1.0.10-99

**Comment by comp500** [comment]
It also seems to work fine with Forge 14.23.5.2778 and LLibrary 1.7.15, so the regression is probably between versions 1.7.15 and 1.7.17 of LLibrary.
