### ISSUE TITLE
LLibrary issues - Forge request.

### ISSUE THREAD

**Issue by Darkfiend009** [iLexiconn/LLibrary#118]
I had an issue that i took to the Forge forums and i posted my log for them to inspect. They responded back to the issue i was having but also asked me to post my log here for you as they said LLibrary was doing some things that you should be aware of.

I don't know specifically what they are referring to but i wanted to make sure i passed the information along. Here's the log. 
[2019-01-09-2.log](https://github.com/iLexiconn/LLibrary/files/2741718/2019-01-09-2.log)

**Comment by vico93** [comment]
Adding for context part of diesieben07's:

>Apart from LLibrary being  **completely broken and doing terrible things** (you should report this log to them) the report does not contain any errors.

**Comment by vico93** [comment]
#119, #117 related (?)

**Comment by Gegy** [comment]
Yeah, these seem likely related. Thanks for the report. :)
