### ISSUE TITLE
1.7.17 Exception in LLibrary causes minecraft to crash on startup.

### ISSUE THREAD

**Issue by PongoSapiens** [iLexiconn/LLibrary#119]
So this is an odd one, I have a modpack I created (Rum Raisin) which includes Wings and hence LLibrary, and on start up I get an exception thrown from LLIbrary and then a later exception in ElecCore which causes minecraft to crash. If I remove ElecCore, the exception from LLibrary remains, but the exception that crashes minecraft moves to a different mod. If I remove enough other mods, I can get minecraft to stop crashing, but the exception from LLibrary remains. If I *just* remove Wings and LLibrary, then the modpack starts correctly with none of the exceptions seen from other mods when LLibrary was present - so my guess is that the exception from LLibrary is interrupting one phase of startup so that some other mods don't get correctly initialized.

The exception form LLIbrary is:
[23:40:22] [main/ERROR] [LLibrary Core]: Failed to force load class net.minecraft.entity.player.EntityPlayerMP
java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityPlayerMP
...
Caused by: java.lang.ClassCircularityError: net/minecraft/entity/player/EntityPlayer

Note that this happens both on a client install (Win10 Home, Twitch Launcher) and on a server install (linux fedora 29 openjdk1.8)
And it's for Minecraft 1.12.2, forge loader 14.23.5.2793.
[2019-01-08-1.log.gz](https://github.com/iLexiconn/LLibrary/files/2742941/2019-01-08-1.log.gz)

**Comment by opaillya** [comment]
I tested this, and the issue happens when using Forge version 14.23.5.2779 or above; this doesn't happen with 14.23.5.2778 or below.

**Comment by EnragedN3wb** [comment]
Sadly I can confirm that this still occurs on version 1.7.17, at least with forge 14.23.5.2811 & 14.23.5.2810.

**Comment by EnragedN3wb** [comment]
More info: The crash seems intermittent & doesn't happen on every startup, but when it happens this is the Debug log for it(it doesn't seem to create an actual crash log).

https://pastebin.com/5uwWe47c

**Comment by EnragedN3wb** [comment]
Any word on this?
