### ISSUE TITLE
Llibrary turns Mo Creatures mobs invisible

### ISSUE THREAD

**Issue by mser7** [iLexiconn/LLibrary#120]
![2019-01-18_17 17 30](https://user-images.githubusercontent.com/22555489/51381149-f0505280-1b45-11e9-99bf-2a6e013114e4.png)
![2019-01-18_17 17 37](https://user-images.githubusercontent.com/22555489/51381152-f0505280-1b45-11e9-811a-ebe04d50f3f1.png)

**Comment by Gegy** [comment]
Could you send a log from an instance where this occurs?

**Comment by mser7** [comment]
Instance? Sure... I use MultiMC too, I will see what I can dig up

**Comment by Gegy** [comment]
I don't mean an instance as in a MultiMC instance. That was not very clear, apologies. :P
I more mean a session.

**Comment by mser7** [comment]
Oh yes, I did updated to the latest version, yet this is still occur

**Comment by mser7** [comment]
This is difficult, as the only log I know how to accesd is MultiMC's console log as my game is running

**Comment by Gegy** [comment]
`latest.log` is created after a session is closed

**Comment by mser7** [comment]
And the bug also occur as I started my game, and persist, only when I removed llibrary that it stopped, so Im not sure about that instance, or session

**Comment by mser7** [comment]
I am sorry, llibrary wasnt the issue, it was custom mob spawner.

**Comment by Gegy** [comment]
Ah alright, np. :)
