### ISSUE TITLE
Llibrary Crashes While Loading

### ISSUE THREAD

**Issue by Avtocx** [iLexiconn/LLibrary#123]
I keep trying to get on a mod pack named Wild West, but every time my game crashes before it even gets half way through loading. The launcher will try to load Llibrary for 131 seconds before finally giving up on it. From what I see, my Java is up to date, and I have enough memory allocated. I tried to remove Llibrary and its dependent (Jurassicraft), and the game loaded up fine. However, I want to play on the server pack, so it creates a bit of a problem. I tried to just put Llibrary in there instead of both Jurrasic and itself, and I still got the same problem. Please help me. This pack brings back a nostalgic feeling, and I'm ready to feel it again.

Log of just Llibrary:
[fml-client-latest.log](https://github.com/iLexiconn/LLibrary/files/2839064/fml-client-latest.log)

Crash Report:
[crash-2019-02-06_19.11.14-client.txt](https://github.com/iLexiconn/LLibrary/files/2839065/crash-2019-02-06_19.11.14-client.txt)

Thanks :)

**Comment by Gegy** [comment]
Hey, LLibrary 1.7.10 is no longer supported. Sorry! :(
