### ISSUE TITLE
Llibrary causes crash at startup 1.12.2

### ISSUE THREAD

**Issue by unsocialnerd** [iLexiconn/LLibrary#127]
Llibrary is causing mincraft 1.12.2 to crash at startup 
[2019-02-26-7.log](https://github.com/iLexiconn/LLibrary/files/2908501/2019-02-26-7.log)

**Comment by Gegy** [comment]
Judging by the log file it does not look like you have LLibrary installed

**Comment by Froted** [comment]
> Judging by the log file it does not look like you have LLibrary installed

Why did you close this when it would display an error message stating he is missing LLibrary? The problem was his game won't open when he downloaded it. I'm having the same problem he is having. I would've figured I could've gotten the fix here but I guess not.
