### ISSUE TITLE
Need help finding the right version

### ISSUE THREAD

**Issue by AnnaTheKitty** [iLexiconn/LLibrary#132]
I am trying to use LLibrary for my modpack, I am using the recommended version of forge which is 14.23.5.2768 for version 1.12.2 of minecraft. I have downloaded your mod a couple of times but I couldn't find anything or the right version, can you help me out and give me the right version or the link to it? Thanks.

**Comment by AnnaTheKitty** [comment]
Finally founded it nvm

**Comment by FlamingSharky** [comment]
which was it for that one? i cant find it
