### ISSUE TITLE
Won't load with LLibrary 1.7.14

### ISSUE THREAD

**Issue by Froted** [iLexiconn/LLibrary#134]
Every time i try opening Minecraft with LLibrary 1.7.14 an error message pops up and tells me an unexpected error has occured. I've tried getting rid of it and my game actually opens but for jurrasicraft i need it still.

**Comment by Gegy** [comment]
Could you please share the crash report?

**Comment by GhostZero91** [comment]
[crash-2019-04-12_22.26.53-server.txt](https://github.com/iLexiconn/LLibrary/files/3075066/crash-2019-04-12_22.26.53-server.txt)

**Comment by GhostZero91** [comment]
thats my crash report on 1.7.14

**Comment by GhostZero91** [comment]
on my server with latest forge for minecraft 1.12.2

**Comment by Gegy** [comment]
Could you please try the latest version? 1.7.18 is latest

**Comment by GhostZero91** [comment]
[crash-2019-04-12_22.17.33-server.txt](https://github.com/iLexiconn/LLibrary/files/3076009/crash-2019-04-12_22.17.33-server.txt)

**Comment by GhostZero91** [comment]
i have tried every 1.12.2 version
at least that what it feels like

**Comment by Gegy** [comment]
Does this occur if you have just LLibrary installed? This seems to be an issue with a mod that is dependent on LLibrary

**Comment by GhostZero91** [comment]
dragon mounts 2 need LLlibrary to function

**Comment by GhostZero91** [comment]
I just checked the latest version and it works, but thank you anyway for the help and keep up the good work :)
