### ISSUE TITLE
Llibrary Ran Into A Problem - Dedicated Server

### ISSUE THREAD

**Issue by MokahTGS** [iLexiconn/LLibrary#135]
No idea what is happening but I'm getting tons of crash logs, while still being able to log onto our dedicated server.  The logs aren't super helpful.

This appears on screen and won't go away, they keep popping up:
https://www.dropbox.com/s/x10qrlkl3wfvokk/2019-04-18_16.37.04.png?dl=0

Crash log, that isn't a crash: https://pastebin.com/kgycNSVH

Mod List: https://pastebin.com/x2vmAZ4f

Forge 2825
LLibrary 1.7.18-1.12.2

**Comment by Gegy** [comment]
This doesn't look like an LLibrary issue -- LLibrary doesn't touch that code at all. This seems to be an error which VanillaFix is misreporting to be LLibrary.
