### ISSUE TITLE
Issue with Llibrary and Mowzies Mobs in a server

### ISSUE THREAD

**Issue by alejvro** [iLexiconn/LLibrary#163]
I´m running version 1.12.2 and Forge 14.23.5.2847

[latest.log](https://github.com/iLexiconn/LLibrary/files/4340008/latest.log)

**Comment by pau101** [comment]
> Mod mowziesmobs (Mowzie's Mobs) requires [llibrary@[1.7.9,)]

You need to update LLibrary

**Comment by alejvro** [comment]
yeah but i got a server with llibrary 1.7.19 and Mowzies Mobs 1.5.4 that works, but when i enter with Llibrary 1.7.9 it doesnt

**Comment by pau101** [comment]
The error is specifying you're not running 1.7.9 on your client.
