### ISSUE TITLE
1.15.2 plans?

### ISSUE THREAD

**Issue by willwh** [iLexiconn/LLibrary#170]
Are there any plans for a `1.15.2` port of the lib? Is there anything I can do to help? Just getting my feet wet in minecraft dev.... looks like `llibrary` is heavily used in a lot of mods pre `1.15.2`, and would be a good one to get familiar with!

**Comment by Skydragonsz** [comment]
same question but for 1.16.4

**Comment by Gegy** [comment]
It is not planned to update LLibrary beyond any critical fixes
