### ISSUE TITLE
Ticking Entity Error Keeps crashing game

### ISSUE THREAD

**Issue by kthomas852** [iLexiconn/LLibrary#179]
This error keeps happening with several of the Dinosaur species and the feeder when using in conjunction with the Jurassic Craft mod.  Crash logs keep reporting the issue is related to llibrary mod.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 11/7/20 5:52 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at org.jurassicraft.server.entity.ai.navigation.DinosaurWalkNodeProcessor.getSafePoint(DinosaurWalkNodeProcessor.java:126)
	at org.jurassicraft.server.entity.ai.navigation.DinosaurWalkNodeProcessor.func_186320_a(DinosaurWalkNodeProcessor.java:57)
	at net.minecraft.pathfinding.PathFinder.func_186335_a(SourceFile:82)
	at net.minecraft.pathfinding.PathFinder.func_186334_a(SourceFile:40)
	at net.minecraft.pathfinding.PathFinder.func_186336_a(SourceFile:30)
	at net.minecraft.pathfinding.PathNavigate.func_179680_a(SourceFile:114)
	at net.minecraft.pathfinding.PathNavigateGround.func_179680_a(SourceFile:51)
	at net.minecraft.pathfinding.PathNavigate.func_75488_a(SourceFile:93)
	at net.minecraft.pathfinding.PathNavigate.func_75492_a(SourceFile:143)
	at org.jurassicraft.server.block.entity.FeederBlockEntity.func_73660_a(FeederBlockEntity.java:325)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.jurassicraft.server.entity.ai.navigation.DinosaurWalkNodeProcessor.getSafePoint(DinosaurWalkNodeProcessor.java:126)
	at org.jurassicraft.server.entity.ai.navigation.DinosaurWalkNodeProcessor.func_186320_a(DinosaurWalkNodeProcessor.java:57)
	at net.minecraft.pathfinding.PathFinder.func_186335_a(SourceFile:82)
	at net.minecraft.pathfinding.PathFinder.func_186334_a(SourceFile:40)
	at net.minecraft.pathfinding.PathFinder.func_186336_a(SourceFile:30)
	at net.minecraft.pathfinding.PathNavigate.func_179680_a(SourceFile:114)
	at net.minecraft.pathfinding.PathNavigateGround.func_179680_a(SourceFile:51)
	at net.minecraft.pathfinding.PathNavigate.func_75488_a(SourceFile:93)
	at net.minecraft.pathfinding.PathNavigate.func_75492_a(SourceFile:143)
	at org.jurassicraft.server.block.entity.FeederBlockEntity.func_73660_a(FeederBlockEntity.java:325)

-- Block entity being ticked --
Details:
	Name: jurassicraft:feeder // org.jurassicraft.server.block.entity.FeederBlockEntity
	Block type: ID #1367 (tile.feeder // org.jurassicraft.server.block.machine.FeederBlock // jurassicraft:feeder)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (-773,70,-136), Chunk: (at 11,4,8 in -49,-9; contains blocks -784,0,-144 to -769,255,-129), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Actual block type: ID #1367 (tile.feeder // org.jurassicraft.server.block.machine.FeederBlock // jurassicraft:feeder)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Mairtz'/26666, l='world', x=-740.71, y=67.08, z=-211.99]]
	Chunk stats: ServerChunkCache: 713 Drop: 0
	Level seed: -8084020387070485974
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (72,64,252), Chunk: (at 8,4,12 in 4,15; contains blocks 64,0,240 to 79,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 90547304 game time, 109297 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 124803 (now: false), thunder time: 111292 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.0-87-generic
	Java Version: 1.8.0_232, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 5491929176 bytes (5237 MB) / 7257194496 bytes (6921 MB) up to 7257194496 bytes (6921 MB)
	JVM Flags: 2 total; -Xmx7000M -Xms7000M
	IntCache: cache: 0, tcache: 0, allocated: 14, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 34 mods loaded, 34 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version       | Source                                         | Signature                                |
	|:------ |:------------------- |:------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2        | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                 | 9.42          | minecraft.jar                                  | None                                     |
	| LCHIJA | FML                 | 8.0.99.99     | forge-1.12.2-14.23.5.2854-universal.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2854  | forge-1.12.2-14.23.5.2854-universal.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | battletowers        | 1.6.5         | BattleTowers-Mod-1.12.2.jar                    | None                                     |
	| LCHIJA | betternether        | 0.1.8.6       | Better-Nether-Mod-1.12.2.jar                   | None                                     |
	| LCHIJA | buildcraftlib       | 7.99.24.1     | BuildCraft-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | buildcraftcore      | 7.99.24.1     | BuildCraft-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | buildcraftbuilders  | 7.99.24.1     | BuildCraft-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | buildcrafttransport | 7.99.24.1     | BuildCraft-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | buildcraftsilicon   | 7.99.24.1     | BuildCraft-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | buildcraftenergy    | 7.99.24.1     | BuildCraft-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | ic2                 | 2.8.186-ex112 | Industrial-Craft-2-Mod-Experimental-1.12.2.jar | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | jei                 | 4.15.0.297    | jei_1.12.2-4.15.0.297.jar                      | None                                     |
	| LCHIJA | forestry            | 5.8.2.408     | Forestry-Mod-1.12.2.jar                        | None                                     |
	| LCHIJA | buildcraftcompat    | 7.99.24.1     | BuildCraft-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | buildcraftfactory   | 7.99.24.1     | BuildCraft-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | buildcraftrobotics  | 7.99.24.1     | BuildCraft-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | cat                 | 0.1           | Caves-And-Dungeons-Mod-1.12.2.jar              | None                                     |
	| LCHIJA | cctweaked           | 1.89.2        | cc-tweaked-1.12.2-1.89.2.jar                   | None                                     |
	| LCHIJA | computercraft       | 1.89.2        | cc-tweaked-1.12.2-1.89.2.jar                   | None                                     |
	| LCHIJA | gottschcore         | 1.13.1        | GottschCore-mc1.12.2-f14.23.5.2768-v1.13.1.jar | None                                     |
	| LCHIJA | dungeons2           | 1.7.1         | Dungeons-2-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | flansmod            | 5.5.2         | Flan's Mod-1.12.2-5.5.2.jar                    | None                                     |
	| LCHIJA | flansmodapocalypse  | 1.0           | Flan's Mod-1.12.2-5.5.2.jar                    | None                                     |
	| LCHIJA | immersiveruins      | 1.0.0         | Immersive-Ruins-Mod-1.12.2.jar                 | None                                     |
	| LCHIJA | lootablebodies      | 2.4.0         | Lootable-Bodies-Mod-1.12.2.jar                 | None                                     |
	| LCHIJA | cfm                 | 6.3.1         | MrCrayfishs-Furniture-Mod-1.12.2.jar           | None                                     |
	| LCHIJA | railcraft           | 12.0.0-beta-5 | Railcraft-Mod-1.12.2.jar                       | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | shipwrecks_winslow  | 2.0.0         | Shipwrecks-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | travelersbackpack   | 1.0.30        | Travelers-Backpack-Mod-1.12.2.jar              | None                                     |
	| LCHIJA | twilightforest      | 3.9.888       | Twilight-Forest-Mod-1.12.2.jar                 | None                                     |
	| LCHIJA | llibrary            | 1.7.19        | llibrary-1.7.19-1.12.2.jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | jurassicraft        | 2.1.23        | JurassiCraft-1.12.2-2.1.23.jar                 | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['Mairtz'/26666, l='world', x=-740.71, y=67.08, z=-211.99]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Gegy** [comment]
This is an issue in JurassiCraft :)
