### ISSUE TITLE
Maven is empty

### ISSUE THREAD

**Issue by Sunconure11** [iLexiconn/LLibrary#18]
Is this intentional? I'm going to use this as a dependency for something in the future.

Edit: Your page got hacked. https://www.dropbox.com/s/ixh4dqbp7xdxcn2/Screenshot%202016-08-28%2013.51.52.png?dl=0

**Comment by iLexiconn** [comment]
Not a hacker, just me being stupid and messing up the server. I'm currently setting up a new one. (the hack thing is a joke)

**Comment by JamiesWhiteShirt** [comment]
+5...
