### ISSUE TITLE
LLibraly 1.12.2

### ISSUE THREAD

**Issue by VuSom** [iLexiconn/LLibrary#187]

**Comment by VuSom** [comment]
Dowlao

**Comment by Kasia1403** [comment]
What ?! Maybe it's the same as mine ?

**Comment by Kasia1403** [comment]
#189

**Comment by Kasia1403** [comment]
Where's Your crash report file ?

**Comment by Kasia1403** [comment]
@VuSom, please answer.

**Comment by Kasia1403** [comment]
@VuSom This mod is called LLibrary, not LLibraly  !!! You stupid fucking kid !!! Go away from here !!!

**Comment by Kasia1403** [comment]
@iLexiconn I have a serious problem ! I need HELP !!!
