### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by InsaneJ** [iLexiconn/LLibrary#19]
After having updated from llibrary-1.5.1-1.10.2 to llibrary-1.6.0-1.10.2 the following crash happens:
http://paste2.org/1dpJCKkA

**Comment by K4N0** [comment]
http://pastebin.com/vwpjxncq
Same,

**Comment by iLexiconn** [comment]
Sorry for that, forgot something while releasing. Will be fixed in the next release.

**Comment by knoxhack** [comment]
I was about to report this. got the same crash while updating the MMD Dev Pack

**Comment by K4N0** [comment]
Thank You!!

**Comment by sandalle** [comment]
This seems to be fixed in LLibrary 1.7.0-1.10.2, thank you. :)
