### ISSUE TITLE
Llibrary now permanenty crashes on 1.7.10 no matter how I try to load up the mod...

### ISSUE THREAD

**Issue by branman5949** [iLexiconn/LLibrary#202]
whenever i try booting up LLibrary it gives me this crash:
[crash-2024-04-17_17.59.55-client.txt](https://github.com/iLexiconn/LLibrary/files/15017754/crash-2024-04-17_17.59.55-client.txt)

and here are the logs:
[latest.log](https://github.com/iLexiconn/LLibrary/files/15017758/latest.log)
[fml-client-latest.log](https://github.com/iLexiconn/LLibrary/files/15017759/fml-client-latest.log)

Reminder, I am only using 4 mods: Llibrary, AnimationAPI, MowziesMobs, and Optifine. and even then when i take those 3 mods out, LLibrary still crashes no matter what and the crashed just started to this day...

**Comment by DeputyDelusional** [comment]
Same here, was working fine earlier in the day.
I have the exact same cause for the crash.

This line defines the issue: 

> Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1

followed by:

> at net.ilexiconn.llibrary.client.ClientProxy.<clinit>(ClientProxy.java:34)

I went to the ClientProxy.class file, as cited, inside the mods .jar file and, by using a java decompiler, I have been able to read its contents.
Found this on line 34:
`public static final String[] PATRONS = (String[])(new Gson()).fromJson(WebUtils.readPastebin("aLjMgBAV"), String[].class);`

Heres my crash log from earlier. 
[crash-2024-04-17_20.55.14-client.txt](https://github.com/iLexiconn/LLibrary/files/15018383/crash-2024-04-17_20.55.14-client.txt)

Pretty much identical, has a few more mods but none of the others throw out errors nor have I had any issues with them or llibrary before today.

**Comment by branman5949** [comment]
> Same here, was working fine earlier in the day. I have the exact same cause for the crash.
> 
> This line defines the issue:
> 
> > Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1
> 
> followed by:
> 
> > at net.ilexiconn.llibrary.client.ClientProxy.(ClientProxy.java:34)
> 
> I went to the ClientProxy.class file, as cited, inside the mods .jar file and, by using a java decompiler, I have been able to read its contents. Found this on line 34: `public static final String[] PATRONS = (String[])(new Gson()).fromJson(WebUtils.readPastebin("aLjMgBAV"), String[].class);`
> 
> Heres my crash log from earlier. [crash-2024-04-17_20.55.14-client.txt](https://github.com/iLexiconn/LLibrary/files/15018383/crash-2024-04-17_20.55.14-client.txt)
> 
> Pretty much identical, has a few more mods but none of the others throw out errors nor have I had any issues with them or llibrary before today.

Hey good news!!! some guy helped me out with the crash. this mod fixes the issue!!! https://modrinth.com/mod/bugtorch/version/1.2.13
