### ISSUE TITLE
Crash upon Startup (Initializing Game)

### ISSUE THREAD

**Issue by iKarTehFox** [iLexiconn/LLibrary#24]
So, whenever I tried to update to the latest version of LLibrary, my game kept crashing when I tried to start it up. The description says, "Initializing Game". I already knew that because it crashed when it was Initializing the Mods. Simple :) I had to revert back to the 1.5.1 version to save my game. Any help?

**Comment by jochuan** [comment]
https://github.com/iLexiconn/LLibrary/issues/19
