### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by jochuan** [iLexiconn/LLibrary#25]
my game crashed when i was entering in my world and some time later while i was walking i am using 1.10.2 with the latest forge and llibrary 1.5.1
https://gist.github.com/jochuan/84af5805187743f2b07fda85741abab3

**Comment by iLexiconn** [comment]
Not LLibrary

**Comment by pau101** [comment]
Could you provide the crash report for the other time it crashed? It's probably not an issue caused by LLibrary but seeing the other crash report would help decide that.
