### ISSUE TITLE
LLibrary makes headcrumbs statue invisible

### ISSUE THREAD

**Issue by mser7** [iLexiconn/LLibrary#28]
Happen in Minecraft version 1.7.10 when having both LLibrary and Headcrumbs installed. When building a statue from the headcrumbs mod using two clay blocks and a headcrumbs's player head on top, the statue becomes invisible but still can be interact.

**Comment by iLexiconn** [comment]
Sorry, but the 1.7.10 version isn't getting any updates anymore.
