### ISSUE TITLE
Qubble/LLibrary crash

### ISSUE THREAD

**Issue by leojaxx** [iLexiconn/LLibrary#29]
Not sure if this is Qubble or LLibrary but I'm assuming LLibrary so I'm posting here

The game loads but as soon as I hit the "Q" I get this ...

[Crash Report](http://pastebin.com/JnnTuk1T)

Thanks

**Comment by Gegy** [comment]
You must use LLibrary 1.5.1 until Qubble has been ported to 1.7.0. :)

**Comment by leojaxx** [comment]
Awesome, thanks. And I appreciate the quick response. Maybe have the link on the Curse page go to the 1.5.1 version? Or something similar? Just a thought. 

Thanks again
