### ISSUE TITLE
LLibrary freeze at preInitailization phase

### ISSUE THREAD

**Issue by jahtim** [iLexiconn/LLibrary#30]
When I'm playing Fossil and Archeology in 1.7.10 i need to install LLibrary. We have a bad Internet in India and so I don't want to update any mod. When I install LLibrary, it freezes at preInitailization phase on minecraft loading. I Guess it was the bad Internet that make the game freeze. I tried turn off anything in config of LLibrary, but the game still freezes.

Will there be a method that make Fossil and Archeology runing and the game not freezing, WITHOUT INTERNET?

**Comment by Gegy** [comment]
Unfortunately since the 1.7.10 versions will not be getting any updates this will not be fixed on that, although F/A will be updated to 1.10.2 at some point.

**Comment by jahtim** [comment]
hey, what if I can update 1.7.10 by myself? I really need to make my modpack running? I could change some code in branch 1.7.10.

**Comment by Gegy** [comment]
Sure - if you'd like to.
