### ISSUE TITLE
Should LLibrary's update checker be deprecated in favor of Forge's?

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [iLexiconn/LLibrary#39]
Minecraft Forge provides an [update checker](https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/) that functions very similarly to LLibrary's and is just as easy (if not easier) to use.

Modded minecraft is plagued by a plethora of different solutions to update checking, the most annoying of which is chat messages when logging in to a world. LLibrary handles this rather elegantly, as proven by how Forge added a very similar, non-intrusive system. I think the LLibrary update checker should be deprecated in favor of Forge's.

Why?

* The Forge update checker is battle tested and robust. I have had crash issues with LLibrary's update checker when the JSON parser got unexpected input. This has since been fixed, but there might be more dormant issues within LLibrary's update checker. The Forge update checker is used by more mods, thus held to higher standards, making such issues less likely to appear.

* To unify mod update checking. Forge added its update checker so you don't have to implement your own solutions.

* To do something with the U button. I personally dislike seeing the U button on the main menu because it is rarely useful. Ideally all mods that need updating should be available in one place, and this place could be the mods list which you can access with the Mods button that has a flashing icon when updates are available.

**Comment by WesCook** [comment]
Please do consider this change.  The "U" icon is very annoying as a pack author, and even if it's replaced with a custom main menu there is still a notice at the bottom: "LLibrary has detected mods are out of date".

Ultimately there's no need for this in modpacks, which is how most mods are played.  Only pack authors can make that change, but it's end-users that are receiving the notifications.

Currently I'm keeping LLibrary back a version on purpose to prevent a texture issues with Mowzie's Mobs (they should fix it on their end soon).  I don't want to see the update prompt every time I load the game in the mean time, though.

To me moving to Forge's system is the best option, but if not then a config to disable the update prompt and "U" button would be a much appreciated alternative.

**Comment by Gegy** [comment]
@WesCook I'm not sure about the version you are using for Mowzie's Mobs, but I'm fairly sure there is a config option to disable update checking.

**Comment by JamiesWhiteShirt** [comment]
LLibrary's configurations are saved in an NBT file. This makes it almost impossible to disable it without using the configuration GUI.

**Comment by WesCook** [comment]
Ah, it didn't even occur to me that an in-game menu might exist.  I searched for a .cfg file but couldn't find one.  Thanks for the heads up!

**Comment by Gegy** [comment]
Update checker has been deprecated as of `1.7.5`
