### ISSUE TITLE
Friend is having issues trying to get a workspace with this mod working

### ISSUE THREAD

**Issue by Sunconure11** [iLexiconn/LLibrary#47]
http://pastebin.com/vkYFT0D8

Any known fixes? I set it to use the proper mappings and what not.

**Comment by Sunconure11** [comment]
Relevant files, if needed:

https://github.com/Um-Mitternacht/Wiccan_Arts/blob/1.10.2/gradle.properties

https://github.com/Um-Mitternacht/Wiccan_Arts/blob/1.10.2/build.gradle

**Comment by Gegy** [comment]
Looks like the maven certificate has expired

**Comment by Sunconure11** [comment]
How can that be resolved? Or would that have to be done on your end?

**Comment by iLexiconn** [comment]
@jriwanek

**Comment by Gegy** [comment]
This has already been resolved.

**Comment by AlexModGuy** [comment]
ripper ohney
