### ISSUE TITLE
Crash with stable_32 mappings

### ISSUE THREAD

**Issue by Sunconure11** [iLexiconn/LLibrary#51]
https://pastebin.com/HjyTQNmw

Happens in a dev environment

**Comment by JamiesWhiteShirt** [comment]
1.7.6 for 1.11.2 uses `snapshot_20161220` mappings. The switch to `stable_32` mappings is committed but not published. You have to do either of the following:

1. Use `snapshot_20161220` or some compatible mapping in your dev environment.
2. Build your own version of LLibrary with updated mappings and depend on it.
3. Get an official build out. It seems there are no changes to release at the moment, though.

**Comment by Gegy** [comment]
1.7.7 has updated to `stable_32`
