### ISSUE TITLE
LLibrary crashes with later versions of Forge

### ISSUE THREAD

**Issue by Sunconure11** [iLexiconn/LLibrary#52]
https://pastebin.com/LQ5tskFf

When you get to rewriting this, you might want to look into fixing it.

**Comment by Gegy** [comment]
Can you try this with 1.7.7?

**Comment by PlanetKiller** [comment]
Can confirm using forge-1.11.2-13.20.1.2386-universal. five consecutive and reliable crashes. Hope I don't really want any of the mods that rely on this. Good luck with fixing the problem.

**Comment by Gegy** [comment]
@PlanetKiller Is this with LLibrary 1.7.7? Do you have any other mods installed?

**Comment by Sunconure11** [comment]
I'm pretty sure the issue is gone, at least, on 1.12. I encountered this on a 1.12 pack I am building.

**Comment by PlanetKiller** [comment]
Running minecraft 1.11.2 with 
forge-1.11.2-13.20.1.2386-universal
JurassiCraft-2.0.5
liteloader-1.11.2-SNAPSHOT-release
llibrary-1.7.4-1.11.2
mod-minelittlepony-1.11.2.4-mc1.11.2.litemod

The crash is either from liteloader or mine little pony.
Tried with just forge, Llibrary, and Jurassicraft without crashes.
Going to test without MLP and work the problem from there, with a stick.

I am sad, it seems to be the MLP mod. Liteloader works with another mod.
I can't have a pony eating tyrannosaurs. This does mean I could do two different modpacks that are very similar.
[crash-2017-10-04_16.35.08-client.txt](https://github.com/iLexiconn/LLibrary/files/1357421/crash-2017-10-04_16.35.08-client.txt)

**Comment by Gegy** [comment]
This crash is different from the one in the OP. The issue originates from [LLibrary replacing](https://github.com/iLexiconn/LLibrary/blob/1.11.2/src/main/java/net/ilexiconn/llibrary/server/core/patcher/LLibraryRuntimePatcher.java#L62) the renderLeftArm method, and then [MineLittlePony trying to replace it](https://github.com/MineLittlePony/MineLittlePony/blob/master/src/main/java/com/minelittlepony/mixin/MixinRenderPlayer.java#L146) too, with conditions that are no longer met. Replacing a whole method is dangerous, and LLibrary should not be doing this.
