### ISSUE TITLE
TabulaModelHandler: Domain %s has been added.

### ISSUE THREAD

**Issue by miiichael** [iLexiconn/LLibrary#53]
Did someone forget to printf()? :stuck_out_tongue:

Using llibrary-1.7.7-1.11.2 on forge-1.11.2-13.20.1.2454 (and a bunch of other mods). Noticed this whilst wading through logs resulting from an problem elsewhere...

**Comment by Gegy** [comment]
Interesting, this was supposedly fixed in #36.
