### ISSUE TITLE
1.12.1 release required

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [iLexiconn/LLibrary#54]
The LLibrary core mod requires MC version `"1.12"` which does not match 1.12.1. FML only allows an exact match, so a separate release for 1.12.1 is required.

**Comment by Gegy** [comment]
The 1.12 release is currently broken. This will need to be fixed first.

**Comment by Gegy** [comment]
[1.12.1 port](https://minecraft.curseforge.com/projects/llibrary/files/2474420) was just released.
