### ISSUE TITLE
Lllibrary crashes when using disguise kit from tf2 weapon stuff mod

### ISSUE THREAD

**Issue by Akitori** [iLexiconn/LLibrary#55]
Here's the entirety of the crash here.

To reproduce steps.

1. Get disguise kit.

2. Right click it.

Crash! 

It only occurs because of llibrary i believe. Hmm

[crash-2017-09-21_00.21.22-client.txt](https://github.com/iLexiconn/LLibrary/files/1320054/crash-2017-09-21_00.21.22-client.txt)

**Comment by rafradek** [comment]
This is since LLibrary assumes that a GameProfile of the rendered player has an ID, and so it crashed. I fixed it now by adding failsafe measures.

**Comment by Akitori** [comment]
When will the release be on curseforge if you don't mind me asking so i can test it?

**Comment by rafradek** [comment]
Well it was since i commented
