### ISSUE TITLE
Game crashed!

### ISSUE THREAD

**Issue by 12edqdqx** [iLexiconn/LLibrary#60]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (LLibrary-1.11.2 (1).jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 1/17/18 3:15 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.block.model.FaceBakery.func_178404_a(FaceBakery.java:202)
	at net.minecraft.client.renderer.block.model.FaceBakery.fillVertexData(FaceBakery.java:189)
	at net.minecraft.client.renderer.block.model.FaceBakery.makeQuadVertexData(FaceBakery.java:112)
	at net.minecraft.client.renderer.block.model.FaceBakery.makeBakedQuad(FaceBakery.java:76)
	at net.minecraft.client.renderer.block.model.FaceBakery.func_178414_a(FaceBakery.java:58)
	at BlockModelUtils.makeBakedQuad(BlockModelUtils.java:84)
	at BlockModelUtils.makeModelCube(BlockModelUtils.java:61)
	at BetterGrass.update(BetterGrass.java:73)
	at TextureUtils.resourcesReloaded(TextureUtils.java:295)
	at TextureUtils$1.func_110549_a(TextureUtils.java:338)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at TextureUtils.registerResourceListener(TextureUtils.java:342)
	at net.minecraft.client.renderer.EntityRenderer.frameInit(EntityRenderer.java:2732)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1269)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:112)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 71761816 bytes (68 MB) / 395313152 bytes (377 MB) up to 2147483648 bytes (2048 MB)
	LiteLoader Brand: 1.11.2-SNAPSHOT-r23F62BD-b2-2
	LiteLoader Mods: 1 loaded mod(s)
          - VoxelMap version 1.6.19
	LaunchWrapper: 25 active transformer(s)
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: $wrapper.net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
          - Transformer: $wrapper.net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
          - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx2048m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2579 Optifine OptiFine_1.11.2_HD_U_B5 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2579.jar) 
	U	forge{13.20.1.2579} [Minecraft Forge] (forge-1.11.2-13.20.1.2579.jar) 
	U	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	U	recipehandler{0.8} [NoMoreRecipeConflict] ([合成冲突消除]NoMoreRecipeConflict-0.8(1.11).jar) 
	U	baubles{1.4.6} [Baubles] (Baubles-Mod-1.11.2.jar) 
	U	bloodbaubles{0.0} [Blood Baubles] (BloodBaubles-1.11.2.jar) 
	U	bloodmagic{1.11-2.1.11-80} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.11-80.jar) 
	U	cyclopscore{0.10.9} [Cyclops Core] (CyclopsCore-1.11.2-0.10.9.jar) 
	U	evilcraft{0.10.30} [EvilCraft] (EvilCraft-1.11.2.jar) 
	U	evilcraftcompat{1.0.0} [EvilCraft-Compat] (EvilCraft-1.11.2.jar) 
	U	fastleavedecay{1.2.3} [Fast Leave Decay] (fld[1.11]FastLeaveDecay-1.2.3.jar) 
	U	guideapi{1.8-1.0.0-21} [Guide-API] (Guide-API-1.8-1.0.0-21.jar) 
	U	iceandfire{1.2.1} [Ice and Fire] (Ice-and-Fire-1.11.2.jar) 
	U	improvedbackpacks{1.11.2-1.1.2.0} [Improved Backpacks] (ImprovedBackpacks-1.11.2-1.1.2.0.jar) 
	U	jei{4.8.5.138} [Just Enough Items] (jei_1.12.2-4.8.5.138.jar) 
	U	lazymodder{0.1} [Lazy Modder] (LazyModder-1.11.2.jar) 
	U	llibrary{1.7.6} [LLibrary] (LLibrary-1.11.2 (1).jar) 
	U	lucky{7.4.0} [Lucky Block] (LuckyBlock-1.11.2-Latest.zip) 
	U	magistics{1.11.2-v3.0-alpha} [Magistics] (Magistics-1.11.2-alpha.jar) 
	U	veinminer{0.38.1} [Vein Miner] (VeinMiner-1.11-0.38.1.635+dc28c7d.jar) 
	U	veinminermodsupport{0.38.1} [Mod Support] (VeinMiner-1.11-0.38.1.635+dc28c7d.jar) 
	U	waystones{3.0.17} [Waystones] (Waystones-1.11.2.jar) 
	U	simpletreedrops{1.0} [Simple Tree Drops] (树叶掉落水果和木棍 SimpleTreeDrops 1.0 CN.jar) 
	Loaded coremods (and transformers): 
llibrary (LLibrary-1.11.2 (1).jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4590' Renderer: 'Intel(R) HD Graphics 520'
	Launched Version: HMCL 2.4.1.6
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 520 GL version 4.4.0 - Build 21.20.16.4590, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B5
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 21.20.16.4590
	OpenGlRenderer: Intel(R) HD Graphics 520
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by 12edqdqx** [comment]
Can any guys help me?

**Comment by pau101** [comment]
Do you experience this crash without LLibrary? If not, do you experience it with only OptiFine?

**Comment by 12edqdqx** [comment]
Without LLibrary, it is still crash.  But with only OptiFine, everything is fine.

**Comment by 12edqdqx** [comment]
I solved it, thank you.  I deleted OptiFine, now it is fine.

**Comment by pau101** [comment]
Glad to hear.
