### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by Elias79** [iLexiconn/LLibrary#61]
**`[main/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.ConfigHandler$ConfigContainer:lambda$new$1:48]: java.lang.reflect.InvocationTargetException
`**

https://pastebin.com/ZP1iNUwX

**Comment by Gegy** [comment]
This *should* be fixed for the next update. Is this just logged, or does it cause the game to crash?

**Comment by Elias79** [comment]
Only logged but it is very concerning.

Full log here: https://paste.ee/p/K8KQQ

**Comment by Gegy** [comment]
This is #59, so all should be okay...

**Comment by Elias79** [comment]
Any ETA on the update?

**Comment by Gegy** [comment]
Unless a breaking issue is found, probably will come with LLibrary 1.8. Thanks for the report!

**Comment by Elias79** [comment]
Are we speaking months or weeks here?
