### ISSUE TITLE
crash when breaking pixie hovel

### ISSUE THREAD

**Issue by phyre** [iLexiconn/LLibrary#65]
Hey there!

Not sure if this has been reported thus far,- if it has... my apologies for double reporting.  Got this while testing out the mod before adding it to my server.  

Running forge 1.12.2  14.23.1.2566

This is what the client crash said... but I got the full crash from the crash logs pasted below
The game crashed whilst rendering block entity
The game crashed whilst rendering block entity
Error: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}

WARNING: coremods are present:
  llibrary (BA_DEPG_llibrary-1.7.9-1.12.2.jar)
  MovingWorldCore (BA_DEPF_movingworld-1.12-6.342-full.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 3/22/18 7:58 PM
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at com.github.alexthe666.iceandfire.client.render.tile.RenderPixieHouse.render(RenderPixieHouse.java:36)
	at com.github.alexthe666.iceandfire.client.render.tile.RenderPixieHouse.func_192841_a(RenderPixieHouse.java:18)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:197)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:153)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1008)
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:372)
	at shadersmod.client.Shaders.beginRender(Shaders.java:4150)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1585)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1377)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at com.github.alexthe666.iceandfire.client.render.tile.RenderPixieHouse.render(RenderPixieHouse.java:36)
	at com.github.alexthe666.iceandfire.client.render.tile.RenderPixieHouse.func_192841_a(RenderPixieHouse.java:18)

-- Block Entity Details --
Details:
	Name: minecraft:pixie_house // com.github.alexthe666.iceandfire.entity.tile.TileEntityPixieHouse
	Block type: ID #1040 (tile.iceandfire.pixie_house // com.github.alexthe666.iceandfire.block.BlockPixieHouse)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (13,73,314), Chunk: (at 13,4,10 in 0,19; contains blocks 0,0,304 to 15,255,319), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:197)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:153)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1008)
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:372)
	at shadersmod.client.Shaders.beginRender(Shaders.java:4150)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1585)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['PhyrePhlyZ'/625, l='MpServer', x=12.57, y=73.00, z=313.18]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (29,64,337), Chunk: (at 13,4,1 in 1,21; contains blocks 16,0,336 to 31,255,351), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 15420 game time, 15420 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 115 total; [EntityFishCod['Cod'/264, l='MpServer', x=-14.50, y=58.00, z=237.50], EntityFishCod['Cod'/265, l='MpServer', x=-14.50, y=58.00, z=234.50], EntitySquid['Squid'/268, l='MpServer', x=-14.67, y=58.41, z=276.16], EntityCreeper['Creeper'/269, l='MpServer', x=-9.50, y=11.00, z=289.50], EntityBat['Bat'/270, l='MpServer', x=-10.16, y=18.93, z=299.53], EntityBat['Bat'/271, l='MpServer', x=-9.01, y=24.94, z=390.74], EntityFishCod['Cod'/275, l='MpServer', x=-9.69, y=59.44, z=391.30], EntityCreeper['Creeper'/792, l='MpServer', x=-54.50, y=32.00, z=262.50], EntityFishClownfish['Clownfish'/793, l='MpServer', x=-13.95, y=61.00, z=385.50], EntityFishClownfish['Clownfish'/794, l='MpServer', x=-15.50, y=61.00, z=390.50], EntityFishClownfish['Clownfish'/795, l='MpServer', x=-18.50, y=61.00, z=388.50], EntityFishClownfish['Clownfish'/796, l='MpServer', x=-18.50, y=61.00, z=386.50], EntityCreeper['Creeper'/797, l='MpServer', x=-44.50, y=28.00, z=377.08], EntityCreeper['Creeper'/799, l='MpServer', x=-41.50, y=28.00, z=377.50], EntityFishCod['Cod'/807, l='MpServer', x=56.58, y=58.26, z=294.42], EntityFishCod['Cod'/808, l='MpServer', x=52.50, y=58.00, z=299.50], EntityFishCod['Cod'/809, l='MpServer', x=52.50, y=58.00, z=295.50], EntityFishCod['Cod'/810, l='MpServer', x=48.50, y=58.00, z=291.50], EntityFishCod['Cod'/815, l='MpServer', x=76.50, y=58.00, z=324.50], EntityFishCod['Cod'/816, l='MpServer', x=72.50, y=58.01, z=326.50], EntityFishCod['Cod'/817, l='MpServer', x=73.50, y=58.00, z=328.50], EntityFishCod['Cod'/818, l='MpServer', x=78.50, y=58.00, z=328.50], EntitySkeleton['Skeleton'/322, l='MpServer', x=7.49, y=17.00, z=256.25], EntityFishPufferfish['Pufferfish'/323, l='MpServer', x=2.50, y=58.00, z=270.50], EntityBat['Bat'/324, l='MpServer', x=7.40, y=17.72, z=283.18], EntityCreeper['Creeper'/325, l='MpServer', x=1.50, y=65.00, z=374.50], EntitySpider['Spider'/326, l='MpServer', x=0.50, y=64.00, z=381.50], EntityFishPufferfish['Pufferfish'/839, l='MpServer', x=19.50, y=51.00, z=268.50], EntityFishPufferfish['Pufferfish'/840, l='MpServer', x=24.50, y=51.00, z=267.50], EntityBat['Bat'/328, l='MpServer', x=10.40, y=24.17, z=393.01], EntityFishPufferfish['Pufferfish'/841, l='MpServer', x=21.50, y=51.00, z=265.50], EntityFishPufferfish['Pufferfish'/842, l='MpServer', x=18.50, y=51.00, z=269.50], EntitySkeleton['Skeleton'/362, l='MpServer', x=24.50, y=19.00, z=242.50], EntityFishCod['Cod'/364, l='MpServer', x=18.50, y=53.00, z=271.50], EntityFishCod['Cod'/365, l='MpServer', x=23.50, y=53.00, z=270.50], EntityFishCod['Cod'/366, l='MpServer', x=18.50, y=53.00, z=272.50], EntityFishCod['Cod'/367, l='MpServer', x=25.59, y=53.33, z=272.41], EntitySkeleton['Skeleton'/368, l='MpServer', x=31.50, y=14.00, z=327.50], EntitySkeleton['Skeleton'/369, l='MpServer', x=25.50, y=43.00, z=321.50], EntityPlayerSP['PhyrePhlyZ'/625, l='MpServer', x=12.57, y=73.00, z=313.18], EntityItem['item.item.rottenFlesh'/370, l='MpServer', x=27.90, y=73.00, z=340.60], EntityVillagerMCA['Bertram'/371, l='MpServer', x=41.55, y=73.00, z=339.53], EntitySpider['Spider'/372, l='MpServer', x=23.50, y=73.00, z=361.50], EntitySpider['Spider'/373, l='MpServer', x=19.50, y=73.00, z=360.50], EntitySpider['Spider'/374, l='MpServer', x=21.50, y=73.00, z=359.50], EntitySpider['Spider'/375, l='MpServer', x=17.50, y=73.00, z=359.50], EntityBat['Bat'/383, l='MpServer', x=46.40, y=32.10, z=283.25], EntityCreeper['Creeper'/384, l='MpServer', x=45.50, y=35.00, z=286.50], EntitySkeleton['Skeleton'/385, l='MpServer', x=45.50, y=35.00, z=292.50], EntityVillagerMCA['Annamarie'/386, l='MpServer', x=37.00, y=73.00, z=318.00], EntityVillagerMCA['Emmett'/387, l='MpServer', x=39.19, y=73.00, z=321.63], EntityZombie['Zombie'/388, l='MpServer', x=37.24, y=14.00, z=328.50], EntityZombie['Zombie'/389, l='MpServer', x=35.20, y=14.00, z=326.51], EntityVillagerMCA['Loren'/390, l='MpServer', x=39.00, y=73.00, z=333.00], EntityVillagerMCA['Debi'/391, l='MpServer', x=40.00, y=73.00, z=347.00], EntityVillagerMCA['Alison'/392, l='MpServer', x=46.00, y=73.00, z=346.00], EntityVillagerMCA['Rod'/393, l='MpServer', x=46.00, y=73.00, z=347.00], EntityVillagerMCA['Lieselotte'/394, l='MpServer', x=34.00, y=73.00, z=347.00], EntityVillagerMCA['Broderick'/395, l='MpServer', x=32.50, y=73.00, z=337.45], EntitySkeleton['Skeleton'/396, l='MpServer', x=46.50, y=47.00, z=373.50], EntitySquid['Squid'/402, l='MpServer', x=46.05, y=51.89, z=260.58], EntitySkeleton['Skeleton'/403, l='MpServer', x=57.27, y=28.00, z=268.49], EntityVillagerMCA['Twanda'/407, l='MpServer', x=55.00, y=74.00, z=328.00], EntitySquid['Squid'/408, l='MpServer', x=49.71, y=55.36, z=351.60], EntityItem['item.item.rottenFlesh'/410, l='MpServer', x=58.57, y=73.00, z=345.62], EntitySpider['Spider'/429, l='MpServer', x=66.70, y=76.10, z=318.11], EntityZombie['Zombie'/436, l='MpServer', x=86.50, y=42.00, z=268.50], EntityFishCod['Cod'/437, l='MpServer', x=90.33, y=51.61, z=307.50], EntityZombie['Zombie'/438, l='MpServer', x=80.50, y=29.00, z=324.50], EntityFishPufferfish['Pufferfish'/439, l='MpServer', x=81.50, y=59.00, z=359.50], EntitySkeleton['Skeleton'/195, l='MpServer', x=-48.50, y=12.00, z=234.50], EntitySpider['Spider'/196, l='MpServer', x=-51.50, y=12.00, z=237.50], EntityEnderman['Enderman'/708, l='MpServer', x=-40.50, y=13.00, z=261.50], EntityWitch['Witch'/197, l='MpServer', x=-49.50, y=12.00, z=234.50], EntitySlime['Slime'/709, l='MpServer', x=-38.19, y=13.12, z=258.86], EntityFishCod['Cod'/198, l='MpServer', x=-54.36, y=60.33, z=235.48], EntityCreeper['Creeper'/710, l='MpServer', x=-53.50, y=17.00, z=350.50], EntityFishCod['Cod'/199, l='MpServer', x=-54.50, y=60.00, z=237.50], EntityBat['Bat'/711, l='MpServer', x=-32.83, y=19.03, z=366.54], EntityBat['Bat'/200, l='MpServer', x=-53.10, y=32.32, z=262.52], EntityBat['Bat'/712, l='MpServer', x=-31.54, y=19.58, z=365.89], EntityCreeper['Creeper'/201, l='MpServer', x=-48.50, y=18.00, z=274.50], EntityBat['Bat'/713, l='MpServer', x=-44.24, y=11.58, z=249.57], EntitySkeleton['Skeleton'/202, l='MpServer', x=-52.49, y=43.00, z=303.67], EntityCreeper['Creeper'/203, l='MpServer', x=-49.50, y=39.00, z=344.50], EntitySkeleton['Skeleton'/205, l='MpServer', x=-48.56, y=24.00, z=392.75], EntityFishCod['Cod'/718, l='MpServer', x=-58.50, y=50.00, z=255.50], EntityFishCod['Cod'/719, l='MpServer', x=-62.50, y=50.00, z=255.50], EntityFishCod['Cod'/720, l='MpServer', x=-63.50, y=50.00, z=258.50], EntityFishCod['Cod'/721, l='MpServer', x=-63.46, y=50.19, z=259.44], EntityBat['Bat'/722, l='MpServer', x=-41.70, y=11.06, z=252.96], EntityBat['Bat'/723, l='MpServer', x=-47.43, y=11.58, z=251.57], EntityBat['Bat'/724, l='MpServer', x=-43.50, y=11.58, z=254.45], EntityZombie['Zombie'/734, l='MpServer', x=-54.50, y=17.35, z=354.40], EntityChicken['Chicken'/735, l='MpServer', x=-54.50, y=17.00, z=354.50], EntitySkeleton['Skeleton'/224, l='MpServer', x=-46.50, y=28.00, z=252.31], EntityZombie['Zombie'/736, l='MpServer', x=-52.50, y=18.00, z=351.92], EntitySkeleton['Skeleton'/225, l='MpServer', x=-40.50, y=32.00, z=299.50], EntityWitch['Witch'/226, l='MpServer', x=-43.49, y=32.00, z=296.71], EntityZombie['Zombie'/227, l='MpServer', x=-46.50, y=57.00, z=343.50], EntitySkeleton['Skeleton'/228, l='MpServer', x=-36.75, y=17.00, z=376.46], EntityBat['Bat'/229, l='MpServer', x=-43.13, y=32.02, z=376.28], EntityFishCod['Cod'/742, l='MpServer', x=59.49, y=59.00, z=385.57], EntityFishCod['Cod'/743, l='MpServer', x=56.50, y=59.00, z=382.50], EntityFishCod['Cod'/744, l='MpServer', x=59.50, y=59.00, z=380.50], EntityFishCod['Cod'/745, l='MpServer', x=59.50, y=59.00, z=381.50], EntitySquid['Squid'/235, l='MpServer', x=-22.50, y=59.16, z=276.36], EntityBat['Bat'/236, l='MpServer', x=-28.25, y=45.10, z=323.25], EntitySkeleton['Skeleton'/237, l='MpServer', x=-22.77, y=39.00, z=344.74], EntityCreeper['Creeper'/238, l='MpServer', x=-17.50, y=35.00, z=360.50], EntityBat['Bat'/239, l='MpServer', x=-20.41, y=28.29, z=377.46], EntityCreeper['Creeper'/751, l='MpServer', x=-62.50, y=18.00, z=279.50], EntityZombie['Zombie'/240, l='MpServer', x=-16.50, y=35.00, z=391.50], EntityZombie['Zombie'/241, l='MpServer', x=-16.50, y=35.00, z=392.50], EntityCreeper['Creeper'/758, l='MpServer', x=-59.50, y=12.00, z=264.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Gegy** [comment]
Looks like an issue with Ice and Fire. Report it on their repo, and I'm sure they'll be able to help. :)

**Comment by phyre** [comment]
My bad, not sure how I ended up here posting here,-  musta had too many windows open or something  **shruggie**  Thanks for being understanding and not rude some people would have been!
