### ISSUE TITLE
Error with Galcticraft Mars

### ISSUE THREAD

**Issue by winterspinter** [iLexiconn/LLibrary#7]
I wasn't able to create or load a world so I kept the console open and it appears that there is an incompatibility with Galacticraft Mars. The error occurred specifically when trying to load the Mars dimension while "Building World."

**Comment by winterspinter** [comment]
Also, this only happened after I updated to 1.4.1.

**Comment by iLexiconn** [comment]
Can you send me the log please?

**Comment by winterspinter** [comment]
Wait, never mind. Found the problem.
