### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by Bulldog83** [iLexiconn/LLibrary#71]
Minecraft 1.12.2
Forge 14.23.3.2673
LLibrary 1.7.11

https://gist.github.com/Bulldog83/db97eb0666c67312c8e53aefacd1f22d

**Comment by Sunconure11** [comment]
Can confirm a similar crash.

https://pastebin.com/NEay9bhu

**Comment by Gegy** [comment]
@Sunconure11 This is an issue with LLibrary 1.7.10, update to 1.7.11.
@Bulldog83 Looks like the core jar was not extracted. Send a full log?

**Comment by Bulldog83** [comment]
https://gist.github.com/Bulldog83/38098468e585bbf1d2d78aea0df00913

**Comment by Gegy** [comment]
What about the `debug.log`? Also, have a go with the recommended version of Forge.

**Comment by Bulldog83** [comment]
Mmm. LlibraryCore must be downloaded by LLibrary, right? I keep mods in separate structured folders and load via mod_list.json. May be, problem's in this? How I can download LlibraryCore separate?

**Comment by Bulldog83** [comment]
I've taken it via new profile with only Llibrary loaded.

**Comment by Gegy** [comment]
LLibraryCore is contained within the LLibrary Jar file -- Forge is supposed to extract it out and load it. You could try manually extracting it out.
