### ISSUE TITLE
crash on server start

### ISSUE THREAD

**Issue by Iggyolyous** [iLexiconn/LLibrary#72]
I cant seem to start my server. I keep getting this error.
https://gist.github.com/Iggyolyous/4dcfd0c67404ebd12d6df59cce21f56a

**Comment by Gegy** [comment]
This... is not possible. Huh.

**Comment by Gegy** [comment]
Oh. Delete the `llibrary-core-1.0.4` file in your mods folder. Also update Forge.

**Comment by Iggyolyous** [comment]
forge is as updated as it can be

and i dont have llibrary-core-1.0.4 anywhere in my folders that i can see

**Comment by Gegy** [comment]
Is there a 1.0.5? 
EDIT: Nvm, you don't have LLibrary 1.7.11. Try update.
`| UCHIJAAAA | llibrary | 1.7.10 | llibrary-1.7.10-1.12.2.jar`
