### ISSUE TITLE
Conflict with Spongeforge 1.12.2

### ISSUE THREAD

**Issue by insuusvenerati** [iLexiconn/LLibrary#73]
Version 1.7.11-1.12.2, 1.7.10-1.12.2 of LLibrary currently causes Spongeforge servers to crash on load. 
Spongeforge version 1.12.2-2611-7.1.0-BETA-3002 and later seems to exhibit this issue.

Linking the Spongeforge issue here for visibility as they suggested a possible fix. 

https://github.com/SpongePowered/SpongeForge/issues/2172

Personal crash report from my own testing:
https://gist.github.com/insuusvenerati/3fe9bd99ac57ddf9d30f3363bc3f1509

Latest.log:
Crash is at line 132
https://gist.github.com/insuusvenerati/84d83b69479a9df886ade696c95676a4

**Comment by Gegy** [comment]
Fixed in 1.7.12, thanks for the report. :)
