### ISSUE TITLE
Lag Spikes 

### ISSUE THREAD

**Issue by KAfable** [iLexiconn/LLibrary#76]
Hey, playing Engimatica 2 Expert at the moment and seem to be getting a lot of lag spikes.

I installed TickProfiler - and copied some of the console output when i was profiling for lag spikes (server  operates at 20 tps otherwise).

https://hastebin.com/zokoyawiqo.vbs

There was a lag spike maybe caused by LLibrary according to TickProfiler that lasted over 3 seconds? (actually not too sure, can't read the stacktrace, was only looking at key words), and noticed that this mod was also used by Ice and Fire (which is also in the pack). I was also monitoring the RAM usage and verified it is not a memory leak problem, however CPU utilization does go through the roof during spikes.

Server specs are Xeon 1235 V2 with 6gb dedicated out of 32gb.

**Comment by Gegy** [comment]
Seems like this could be related to #69. Processing the entity map when there are too many entries can be slow.

**Comment by KAfable** [comment]
For what it's worth, I have an Astral Sorcery Lucerna ritual running in my base (prevents mob spawns), and no other chunkloaded areas that I know. Doing `/cofh killall` actually reveals no hostile mobs, is there a way to clear out dragon skeletons / do those count as entities?

**Comment by Gegy** [comment]
@Vyraal1 Apologies for late response -- it's not an issue with too many entities being in your world, it's that LLibrary is keeping all removed entities in a list. This list builds up very quickly, it should only have loaded entities in that list.

**Comment by KAfable** [comment]
@gegy1000 thanks for the response, any idea how to get around this or just wait for an update?

**Comment by Gegy** [comment]
@Vyraal1 An update has been released. :)
