### ISSUE TITLE
Newest release on CurseForge reports itself as tampered on startup.

### ISSUE THREAD

**Issue by Routhinator** [iLexiconn/LLibrary#77]
Freshly downloaded a couple of times..

```
[LLibrary]: Detected invalid fingerprint for file llibrary-1.7.12-1.12.2.jar! You will not receive support with this tampered version of llibrary!
```

**Comment by Gegy** [comment]
Looks like the curseforge buildscript doesn't properly depend on the signJar task. Will fix, thanks. :)

**Comment by Gegy** [comment]
I've uploaded a build with this fixed. Again, thanks for the report!
