### ISSUE TITLE
1.7.9 title, but 1.7.12 file

### ISSUE THREAD

**Issue by mvllvma** [iLexiconn/LLibrary#80]
i need the 1.7.9 version, but every download for it gives me the 1.7.12, even the ones labeled 1.7.9 and it's gotten quite frustrating. any help?

**Comment by Gegy** [comment]
Why do you need 1.7.9? 1.7.12 should work fine, if not better.
Anyway, you can get 1.7.9 for 1.12.2 here: https://minecraft.curseforge.com/projects/llibrary/files/2504999
