### ISSUE TITLE
Crash on death

### ISSUE THREAD

**Issue by NielsPilgaard** [iLexiconn/LLibrary#81]
Hey o/
I hardcrash whenever I die, I'm pretty sure this is related to the recent changes to the list of dead entities you keep (kept?)

Crashlog: https://pastebin.com/RFk0gGeM

llibrary-1.7.13-1.12.2

**Comment by Gegy** [comment]
Thanks for the report! That piece of coded wasn't touched -- odd. Going to wait a moment before releasing a new build, would rather get all the bugs this time.

**Comment by Gegy** [comment]
Interestingly it seems to not happen often for me, though I was able to reproduce it and do see the issue.

**Comment by NielsPilgaard** [comment]
Alright, thank you :)

**Comment by NielsPilgaard** [comment]
Would it be too much to ask that you release it soon? :)

**Comment by Gegy** [comment]
Released 1.7.14.

**Comment by NielsPilgaard** [comment]
Thank you!
