### ISSUE TITLE
Server crash when traveling to Nether - Llibrary 1.7.13

### ISSUE THREAD

**Issue by MachinegunMarty** [iLexiconn/LLibrary#82]
Hi iLexiconn,

I just updated to the latest version of Llibrary (1.7.13)and when i travel to the Nether my server crashes.

I went to the Nether through a Nether portal.

Started my server up again and could login ,but spawned in a wall in the Nether ? 
I used my teleporter (Draconic Dislocator) and teleported to my Nether Teleport location. This went well and was on top of my portal in the Nether.
So i took the Nether portal back to the overworld and the server crashed again.

Attached the server log file for your viewing pleasures ;-)

[2018-06-13-5.log](https://github.com/iLexiconn/LLibrary/files/2098993/2018-06-13-5.log)

I hope it helps you locate the source of the problem.

Good luck !

grtz,

MachinegunMarty

**Comment by Gegy** [comment]
Thanks for the report! This has been resolved with #81, will release a fix soon. :)

**Comment by Gegy** [comment]
Released 1.7.14.
