### ISSUE TITLE
latest update for Llbrary mod breaks minecolonies

### ISSUE THREAD

**Issue by CharCharthemonkey** [iLexiconn/LLibrary#83]
when updating to the latest version of the mod it corrupts the colonies.dat file for minecolonies and only way to fix would be to load from a backup after downgrading and deleting the Llibrary files from the instance folder

**Comment by Gegy** [comment]
Can you confirm that LLibrary is causing this?

**Comment by Raycoms** [comment]
http://paste.ubuntu.com/p/YP2bRNt6K8/

This here

**Comment by Raycoms** [comment]
I'm one of the main devs of minecolonies, it seems you are trying to access the hashCode (in this case removing it from a map for example) before the entity stopped loading.

**Comment by Gegy** [comment]
@Raycoms I'm not quite following. Why is your hashCode throwing an NPE? It is by contract that hashCode should not crash. Your hash should also consistently return the same value.

**Comment by pau101** [comment]
The hash doesn't need to consistently return same value as long as `Object#equals(Object)` reflects the change.

However, there is another violation the `Object#hashCode()` contract. It has the possiblity of two entities being equal determined by [EntityCitizen#equals(Object)](https://github.com/ldtteam/minecolonies/blob/1369e7a93df205312f3e57ab5fb9b8b07542e74b/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L868), but with different hashcodes from [EntityCitizen#hashCode()](https://github.com/ldtteam/minecolonies/blob/1369e7a93df205312f3e57ab5fb9b8b07542e74b/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L879), given by the hash including `super.hashCode()`, which uses `Entity#entityId`, while equality does not include `super.equals(Object)` to involve `Entity#entityId` as well.

The contract states this requirement as:

> If two objects are equal according to the equals(Object) method, then calling the hashCode method on each of the two objects must produce the same integer result.

**Comment by Raycoms** [comment]
It crashes because for some reason your library calls the hash method on one of our citizens before the entity has finished instantiating.
(The only chance an object inside the hash is null)

**Comment by Raycoms** [comment]
I also removed the super.hashCode(), yeah that shouldn't be there, it should be determined by only colonyId and CitizenId.

**Comment by pau101** [comment]
Correct, our code here is happening during capability attachment, which is before an entity has finished instantiation. There just needs to be improved null safety in equals and hashCode of EntityCitizen to support this.

**Comment by Raycoms** [comment]
The problem is, if I make a null check in there, citizens will have an
equal hashCode. Since I don't have the colony yet.
Would have to build a workaround based on something else.

2018-06-17 16:32 GMT-03:00 Paul Fulham <notifications@github.com>:

**Comment by pau101** [comment]
You could fallback to super behavior instead, therefore using entityId.
