### ISSUE TITLE
I can't build my project 

### ISSUE THREAD

**Issue by kave777** [iLexiconn/LLibrary#85]
I can't build my project . 
![34](https://user-images.githubusercontent.com/39627379/41760706-65071b48-75fd-11e8-8fce-3efa1cc240f7.png)
here is my build script : 

buildscript {
    repositories {
    	maven {
        url = "http://maven.bluexin.be/repository/snapshots/"
    }
	    maven {
        name = "ilexiconn"
        url = "https://maven.mcmoddev.com"
    }
        jcenter()
        maven { url = "http://files.minecraftforge.net/maven" }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
		compile "net.ilexiconn:llibrary:1.7.14-1.12.2"
    }
}

**Comment by Gegy** [comment]
You've put the LLibrary maven and dependency in your buildscript block, they need to go outside of that on their own like:
```groovy
buildscript {
    repositories {
        jcenter()
        maven { url = "http://files.minecraftforge.net/maven" }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}

repositories {
    maven { url = "https://maven.mcmoddev.com" }
}

dependencies {
    compile "net.ilexiconn:llibrary:1.7.14-1.12.2"
}
```
