### ISSUE TITLE
Lag in EntityDataHandler.getEntityData

### ISSUE THREAD

**Issue by LemADEC** [iLexiconn/LLibrary#89]
As of llibrary-1.7.14-1.12.2 + iceandfire-1.5.2, profiler reports systematic CPU usage in calls to EntityDataHandler.getEntityData.

![image](https://user-images.githubusercontent.com/4776032/43616798-b69450ca-96be-11e8-9e6e-e10d2f361447.png)

Here it is 0.16% for each mob type, so it scales up pretty fast.
Compared to other mods, similar EntityUpdate events are taking less than 0.05%.

**Comment by Gegy** [comment]
While we could look into optimizing the lookup, this looks like an Ice and Fire issue.

**Comment by LemADEC** [comment]
What would be the best approach to address that issue in Ice and Fire then?

**Comment by Gegy** [comment]
Alright looking at it again there are some possibly significant optimizations that can be made on our side, however doing a capability lookup every tick on every entity is still significantly slow.
https://github.com/iLexiconn/LLibrary/commit/23b9436a8a2405cbbc0e3bee010a835d06e86424

**Comment by Gegy** [comment]
Improved in 1.7.15.
