### ISSUE TITLE
LLibrary Crash - 1.5.0

### ISSUE THREAD

**Issue by viper2g1** [iLexiconn/LLibrary#9]
On startup I get this crash:

https://gist.github.com/viper2g1/5a9548fc524a903d973757348808e425

Upon reverting to 1.4.2 I get a good startup.

This is in a dedicated server running Forge 12.18.1.2011

Mods used:
https://imgur.com/a/h7Jrm

**Comment by viper2g1** [comment]
After trying to update to Forge 12.18.1.2039 (and using the installer to install the libraries associated with that version) this is the crash report that I have.  This is the complete log.  

https://gist.github.com/viper2g1/81345273480bdddc0eb90911eaf86fc7

https://gist.github.com/viper2g1/23c68fcce8a39860d58a4d2d1bf5ba33

If it makes any difference, I'm using McMyAdmin.  Also, reverting to 1.4.2 will startup fine.

**Comment by iLexiconn** [comment]
Fixed in next version :)
