### ISSUE TITLE
Crash w new 1.7.15 on world load

### ISSUE THREAD

**Issue by Knito58** [iLexiconn/LLibrary#90]
https://pastebin.com/51DGzh9R
Forge 14.23.4.2745, MC 1.12.2
no problem with LLibrary 1.7.14-1.12.2

**Comment by Gegy** [comment]
Oops. I see the issue, will resolve it. Thanks for the report.

**Comment by Gegy** [comment]
1.7.15 re-released with fix. :)

**Comment by Knito58** [comment]
Works now. Fix confirmed.
