### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by Potato-Crisps** [iLexiconn/LLibrary#93]
so i got jurassicraft and started it up then this showed up:The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: Could not initialize class org.jurassicraft.JurassiCraft
this is on 1.8.9 pre-release i saw some of the same issues but the solution does not work
Please Help Me!

**Comment by Gegy** [comment]
This is a JurassiCraft issue; you can report it on their issue tracker: https://github.com/JurassiCraftTeam/JurassiCraft2/issues :)
