### ISSUE TITLE
[1.7.15] breaks Mowzie's Mobs.

### ISSUE THREAD

**Issue by kreezxil** [iLexiconn/LLibrary#98]
client crash report on startup https://pastebin.com/19W1yD7v, we're using FORGE 1.12.2-14.23.4.2766

Crossposted in Mowzie's Mobs.

**Comment by kreezxil** [comment]
https://github.com/BobMowzie/MowziesMobs/issues/73

**Comment by marrti** [comment]
yes , crashes on FORGE 1.12.2-14.23.5.2772 too . only working on Forge 1.12.2-14.23.5.2759 !
is as Info .

**Comment by lag42** [comment]
did you try running the game with just llibrary? it might be related to this issue https://github.com/iLexiconn/LLibrary/issues/100

**Comment by AfterRebelion** [comment]
The linked crash (#100 ) only affects Forge 1.12.2-14.23.5.2779 or above. So if this happens on earlier versions, it's not related.
Also that is a really different crash, because it happens before the game starts fully loading, so it doesn't generate a crash report, like this one does.

**Comment by Gegy** [comment]
Looks like forge isn't extracted the contained dep. Could you send a full log, when running on 2772?
